### ISSUE TITLE
java.lang.NumberFormatException: For input string: "us"

### ISSUE THREAD

**Issue by spyhunter99** [batmat/vmstat-analyzer#2]
Exception in thread "main" java.lang.NumberFormatException: For input string: "us"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at net.batmat.vmstatanalyzer.core.model.Stats.<init>(Stats.java:13)
        at net.batmat.vmstatanalyzer.core.analyzer.simpleanalyzer.SimpleAnalyzer.findDominatingConsumer(SimpleAnalyzer.java:101)
        at net.batmat.vmstatanalyzer.core.analyzer.simpleanalyzer.SimpleAnalyzer.getReport(SimpleAnalyzer.java:36)
        at net.batmat.vmstatanalyzer.VmstatMain.main(VmstatMain.java:32)

**Comment by spyhunter99** [comment]
input file was from centos7 with the -w option (wide format)
` vmstat 3 -w `
[nfe.txt](https://github.com/batmat/vmstat-analyzer/files/1063935/nfe.txt)
